# name: Publish

# on:
#   push:
#     branches:
#       - main # Change this to your main branch name

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '7.0.x' # Replace with your desired .NET version

#       - name: Restore dependencies
#         run: dotnet restore  ./src/

#       - name: Publish
#         run: dotnet publish ./src/ --configuration Release --output ./publish -r linux-musl-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:DeleteExistingFiles=true /p:TrimUnusedDependencies=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:StripSymbols=false
        
#       - name: Build Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: ghcr.io/nullchefo/balance-app:latest # Replace with your desired image name and tag
#           file: ./src/Dockerfile-new # Path to your Dockerfile
